# Pose2

A `Pose2` represents a robot's location and orientation in 2D space. It consists of a position `(x, y)` and a rotation `theta`. Its 3-dimensional analog is a `Pose3`. It is included in the top-level `gtsam` package.

<a href="https://colab.research.google.com/github/p-zach/myst-test/blob/main/Pose2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install gtsam

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.4/22.4 MB 2.6 MB/s eta 0:00:00


In [2]:
import gtsam
from gtsam import Pose2, Rot2
import numpy as np

## Initialization

A `Pose2` can be initialized with no arguments, which yields the identity pose, or it can be constructed with a position and rotation.

In [3]:
# Identity pose
p1 = Pose2()
print(p1)

# Pose at (1, 2) and facing north
R = Rot2.fromDegrees(90)
t = (1, 2) # or [1, 2] or np.array([1, 2])
p2 = Pose2(R, t)
print(p2)

(0, 0, 0)

(1, 2, 1.5708)



The pose's properties can be accessed using the appropriate members.

In [21]:
print(f"Location: ({p2.x()}, {p2.y()}); also accessible with translation(): {p2.translation()}")

# .rotation() returns a Rot2 object; the float value can be accessed with .theta()
print(f"Rotation: {p2.theta()}; also accessible with rotation(): {p2.rotation().theta()}")

print(f"Position-rotation 3x3 matrix:\n{p2.matrix()}")

Location: (1.0, 2.0); also accessible with translation(): [1. 2.]
Rotation: 1.5707963267948966; also accessible with rotation(): 1.5707963267948966
Position-rotation 3x3 matrix:
[[ 6.123234e-17 -1.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  2.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


## Operations

Points in the global space can be transformed to and from the local space of the `Pose2` using `transformTo` and `transformFrom`.

In [5]:
import math

global_point = (5, 5)
origin = Pose2(Rot2.fromAngle(math.pi), (1, 1))

# For a point at (1, 1) that is rotated 180 degrees, a point at (5, 5) in global
# space is at (-4, -4) in local space.
transformed = origin.transformTo(global_point)
print(f"{global_point} transformed by {origin} into local space -> {transformed}")

reversed = origin.transformFrom(transformed)
print(f"{transformed} transformed by {origin} into global space -> {reversed}")

(5, 5) transformed by (1, 1, 3.14159)
 into local space -> [-4. -4.]
[-4. -4.] transformed by (1, 1, 3.14159)
 into global space -> [5. 5.]


Bearings (angles) and ranges (distances) can be calculated to points using the associated functions.

In [30]:
p1 = Pose2(Rot2.fromDegrees(90), (-3, -3))
point1 = (-2, -3)
print(f"Bearing from {p1} to {point1}: {p1.bearing(point1).theta()}")

p2 = Pose2(Rot2.fromDegrees(-45), (1, 1))
p3 = Pose2(Rot2.fromDegrees(180), (0, 2))
print(f"Bearing from {p2} to {p3.translation()}: {p2.bearing(p3.translation()).theta()}")

p4 = Pose2(Rot2.fromDegrees(-90), (4, 0))
point2 = (0, 3)
print(f"Range from {p4} to {point2}: {p4.range(point2)}")

Bearing from (-3, -3, 1.5708)
 to (-2, -3): -1.5707963267948966
Bearing from (1, 1, -0.785398)
 to [0. 2.]: 3.141592653589793
Range from (4, 0, -1.5708)
 to (0, 3): 5.0


## Example: SLAM
`Pose2` can be used as the basis to perform simultaneous localization and mapping (SLAM). First, we must initialize the [factor graphs](insert link to factor graph docs)...


In [7]:
# SLAM